openapi: 3.0.3

info:
  title: Authentication service

  license:
    name: MIT
    url: https://github.com/hawks-atlanta/authentication-go/blob/main/LICENSE

  version: TBA

tags:
  - name: Authentication
  - name: Account
  - name: Authorization

paths:
  /login:
    post:
      tags:
        - Authentication
      description: Authenticates to the server
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        '201':
          description: Login succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authorization'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
  /register:
    post:
      tags:
        - Authentication
      description: Register the new user in the service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        '201':
          description: Registration succeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authorization'
        '409':
          description: Username already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
  /challenge:
    post:
      security:
        - bearerAuth: []
      tags:
        - Authorization
      description: Verifies the received token is still valid
      responses:
        '200':
          description: Fresh JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authorization'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
                
  /account/password:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Account
      description: Updates the username password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  oldPassword:
                    type: string
                  newPassword:
                    type: string
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'

  /user/uuid/{username}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Account
      description: Obtain the uuid of an user by its username
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'

  /logs:
    get:
      tags:
        - Logs
      description: Display all system transactions
      responses:
        '200':
          description: Logs found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'

  /logs/user:
    post:
      tags:
        - Logs
      description: Display all system transactions filter by username
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  object:
                    type: object
                    properties:
                      username:
                        type: string
                  itemsPerPage:
                    type: integer
                  page:
                    type: integer
      responses:
        '200':
          description: User logs found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'

  /logs/date:
    post:
      tags:
        - Logs
      description: Display all system transactions filter by date
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  object:
                    type: string
                  itemsPerPage:
                    type: integer
                  page:
                    type: integer
      responses:
        '200':
          description: Logs found by date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    account:
      type: object
      properties:
        uuid:
          type: string
    statusResponse:
      type: object
      properties:
        msg:
          type: string
        succeed:
          type: boolean
    credentials:
      type: object
      properties:
        username:
          type: string
          example: sulcud
        password:
          type: string
          example: password
    authorization:
      type: object
      properties:
        jwt:
          type: string