name: Coverage

on:
  push:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Set up docker environment
        run: docker compose up -d
      - name: Clean
        run: go clean && go clean -cache
      - name: Test
        run: go test -p 1 -count 1 -coverpkg ./... -coverprofile coverage.txt -covermode count ./...
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true
      - name: Clean docker environment
        run: docker compose down --rmi all -v --remove-orphans